---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "louisroyer"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "louisroyer"
    groups:
      pre-commit-deps:
        patterns:
          - "*"
